[package]
name = "betterGI-starter"
version = "0.1.0"
edition = "2021"

[dependencies]
curl = "0.4.47"
directories = "6.0.0"
serde_json = "1.0.135"
sevenz-rust = "0.6.1"
serde = { version = "1.0.217", features = ["derive"] }




